project:
  type: book

book:
  title: "MPAI CAE-ARP book"
  author: "Matteo Spanio"
  date: "2023-11-14"
  chapters:
    - index.qmd
    - sections/intro.qmd
    - sections/mpai.qmd
    - sections/modules.qmd
    - sections/summary.qmd
    - sections/references.qmd

bibliography: references.bib
csl: ieee.csl

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    toc: true
    lof: true
    fontfamily: libertine
    monofont: inconsolata
