# Introduction

During the last years, many archives are facing the need to preserve their heritage from degradation. Digitization plays a central role in the preservation of analog archives by offering a powerful solution to mitigate the challenges associated with physical storage and deterioration by converting analog materials, such as photographs, documents, and audio recordings, into digital formats. In order to guarantee the correct preservation of the original documents and minimize the loss of information, digitization processes cannot be carried out with the so-called “massive approach”, but they require a scientific approach, such as the methodology developed at the *Centro di Sonologia Computazionale* (CSC) for the preservation of audio documents.

The *Centro di Sonologia Computazionale* (CSC) of the Department of Information Engineering at Padua University (@cmj20, @sen22) is a multidisciplinary laboratory actively engaged in music production, audio research, education, and dissemination. A significant area of research at CSC is the digitization and preservation of cultural heritage, especially audio documents, such as speech and music documents (@cmj19, @app18, @jch2016, @tswj14, @dig12).

In dealing with audio documents, the recorded audio signal plays a central role, being the main point of interest, but digitization processes cannot be focused on the recorded audio only. In fact, the methodology developed at CSC gives great importance to metadata gathering and to the completion of the preservation copy, as well as including contextual information, such as photos and video files.
In particular, video documentation allows for capturing additional information beyond the audio itself. At the CSC Lab, the need of including a video-documentation while preserving open-reel audio tapes emerged for the first time while working on the development of preservation strategies for computer music archives, such as the ones belonging to Italian composers Luciano Berio and Luigi Nono. In fact, due to the lack of a standard music score, composers often acted directly onto the surface of the tapes writing notes, markers, and signs to identify the various part of the artwork, and also to give indications to the technicians on stage when performing live tracks in which open-reel tapes were used to add sequences and other musical contents to the solo part.
Furthermore, the video documentation of the entire A/D migration may help in identifying mechanical-related issues (e.g. deformations of the tape that may cause its misalignment with the reading head), splices, and other irregularities on the surface of the tape, such as dirt and loss of magnetic paste. Video documentation helps in preserving this kind of information, which would otherwise be lost.
For these reasons, video documentation is a fundamental part of the preservation methodology adopted by the CSC for the digitization of audio documents, especially within preservation interventions carried out on computer music archives. Together with the Preservation Audio File (.wav, high-res, 24 bit, 96 kHz), the Preservation Copy includes the Preservation Audio Visual File, the video of the digitization process with a low-resolution (typically 16 bit, 48 kHz) audio track recorded for syncing purposes.
Nevertheless, considering the large amount of digitized documents, it may be really time-consuming for archivists to watch several hours of video files for identifying irregularities. Artificial intelligence is a powerful tool that may help the work of archivists and other people involved in preservation interventions, by automatically detecting the points of interest on the surface of the tape. During the years of activity, the CSC preserved and digitized numerous audio archives, working on fonds of different genres, such as classical, ethno and computer music, oral sources, linguistic studies etc. @smc20. For several digitized fonds, together with the large amount of audio files, a related corpus of video documents is available. The video corpus recorded and archived at the CSC lab was used to carry out several research projects and develop computer-vision-based tools for automated video analysis. The outcome of this research was the implementation of the Video Analyser module, part of the recently approved MPAI/IEEE-CAE ARP standard @MPAICAE.
