# Tape Audio Restoration

Open-reel tapes can be recorded at different speeds: 30 ips (76.2 cm/s), 15 ips (38.1 cm/s), 7.5 ips (19.05 cm/s), 3.75 ips (9.53 cm/s), 1.875 ips (4.76 cm/s) and 0.9375 ips (2.38 cm/s). Professional studio machines usually adopt higher speeds, while portable ones usually feature lower speed values to increment the recording length for smaller tapes. Another critical parameter in the tape restoration and preservation is the equalization adopted in the original recording. The equalization curve is used during the recording as pre-emphasis for extending the dynamic range and improving the recorded signal’s Signal to Noise Ratio (SNR). During playback, the inverse post-emphasis curve is applied to restore the original frequency response. Sometimes, given the difficulty of finding fully operating analog machines with the proper speed configuration and equalization settings required by the specific audio document at hand, operators have to perform the digitization adapting to the devices that are available during the process. In other cases, the operator might not detect changes in speed occurred during the original recording. These common situations may introduce errors that cannot be reversed. The Tape Audio Restoration module corrects errors related to changes in speed and those related to the application of wrong equalization curves. At the end of the process, the Tape Audio Restoration AIM provides the Restored Audio Files and an Editing List to the Packager AIM
